Repository AbhiDiva96/75per, pull requests merged in 2024-06, with the labels that each got.

#81 added a copyright message.
  src/pages/footer.css
  src/pages/footer.js
Labels: gssoc, level1

#79 Updated README.md
  README.md
Labels: documentation, gssoc, level1

#94 UPDATING UI OF LOGIN/SignUp Page #49
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
Labels: gssoc, level1

#107 fix #101 and also fix the sign up button state
  src/components/login/LoginSignup.jsx
Labels: gssoc, level1

#104 Updated of readme.md
  README.md
Labels: gssoc, level1

#92 Added the new logo
  public/index.html
  public/logo.png
  src/pages/header.css
  src/pages/header.js
Labels: gssoc, level1

#89 Created Learn.md
  Learn.md
Labels: gssoc, level1

#88 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level1

#78 Updated Footer
  src/pages/footer.css
  src/pages/footer.js
Labels: gssoc, level1

#48 Enhanching the Cards of lecture Page #31 #37
  src/components/page4/lecture.css
  src/components/page4/lecture.js
  src/components/page5(1st)/fstlecture.css
  src/components/page5(1st)/fstlecture.js
  src/components/page6(2nd)/sndlecture.js
Labels: gssoc, level1

#109 Added eye toggling Funtionality
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
Labels: gssoc, level1

#103 back button added
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
Labels: gssoc, level1

#114 Added a review page
  package-lock.json
  package.json
  src/assets/review.jpg
  src/components/review/review.css
  src/components/review/review.jsx
  src/index.js
  src/pages/header.css
  src/pages/header.js
Labels: gssoc, level1

#87 login and signup validation sucessfully added
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
Labels: gssoc, level1

#122 Added Search Functionality
  src/components/page4/lecture.js
  src/components/page4/quantum.css
  src/components/page4/trdquantum.js
  src/components/page5(1st)/fstlecture.js
  src/components/page5(1st)/fstquantum.js
  src/components/page6(2nd)/sndlecture.js
  src/components/page6(2nd)/sndquantum.js
Labels: gssoc

#137 Added About us page
  src/assets/benefits.png
  src/assets/book.png
  src/assets/resource.png
  src/components/about/About.jsx
  src/components/about/about.css
  src/index.js
  src/pages/header.js
Labels: gssoc, level2

#153 Created Dark Mode
  src/Content/context.js
  src/components/about/About.jsx
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
  src/components/page1/Home.css
  src/components/page1/Home.js
  src/components/review/review.jsx
  src/index.js
  src/pages/header.js
Labels: gssoc, level3

#143 [Feature Request]: Add No Results text deisplay on search results
  src/components/noResultsFound/index.css
  src/components/noResultsFound/index.js
  src/components/page4/lecture.js
  src/components/page4/trdquantum.js
  src/components/page5(1st)/fstlecture.js
  src/components/page5(1st)/fstquantum.js
  src/components/page6(2nd)/sndlecture.js
  src/components/page6(2nd)/sndquantum.js
Labels: gssoc, level2

#160 [Feature Request]: Enhancing Ui of PYQ Section #152
  env-example
  src/components/login/LoginSignup.jsx
  src/components/page4/Pyq.css
  src/pages/footer.css
Labels: gssoc, level2

#164 chatbot implementation
  package-lock.json
  package.json
  src/App.js
  src/Content/context.js
  src/components/ChatBot/chatbot.jsx
  src/components/page1/Home.js
  src/components/page2/notice.js
Labels: gssoc, level3

#176 want to Improve Ui of Timetable Section #169
  src/components/imgdata.css
  src/components/imgdata.js
  src/components/page4/timetable.css
  src/components/page4/timetable.js
Labels: gssoc, level2

#200 Fixed Navbar responsiveness
  package-lock.json
  package.json
  src/pages/footer.js
  src/pages/header.css
  src/pages/header.js
  tailwind.config.js
Labels: gssoc, level2

#198 added the cards to all the subjects and also listed all the subjects …
  src/components/page4/Pyq.css
  src/components/page4/pyq.js
Labels: gssoc, level3

#204 footer_added to pages
  src/components/page3/1Year.js
  src/components/page3/2Year.js
  src/components/page3/3Year.js
  src/components/page3/4Year.js
  src/components/page4/syllabus.css
  src/components/page5(1st)/fstlecture.css
  src/components/page6(2nd)/sndquantum.css
Labels: gssoc, level2

#205 4th page improvment
  src/components/page3/4Year.js
Labels: gssoc, level2

#221 [Bug]: Darkmode bugs+Footer #186
  src/components/page1/Home.css
  src/components/page1/Home.js
  src/components/page4/lecture.css
  src/components/page4/lecture.js
  src/components/page4/timetable.js
  src/components/page4/trdquantum.js
  src/components/page5(1st)/fstlecture.js
  src/components/page5(1st)/fstquantum.js
  src/components/page6(2nd)/sndlecture.js
  src/components/page6(2nd)/sndquantum.js
  src/components/review/review.css
  src/components/review/review.jsx
  src/pages/footer.css
Labels: gssoc, level2

#230 chatbot added sucessfully in all pages
  src/components/about/About.jsx
  src/components/layout.js
  src/components/login/LoginSignup.jsx
  src/components/page3/1Year.js
  src/components/page3/2Year.js
  src/components/page3/3Year.js
  src/components/page3/4Year.js
  src/components/page4/pyq.js
  src/components/page4/timetable.js
  src/components/page4/trdquantum.js
  src/components/page5(1st)/fstlecture.js
  src/components/page5(1st)/fstquantum.js
  src/components/page5(1st)/fstsyllabus.js
  src/components/page5(1st)/fsttimetable.js
  src/components/page6(2nd)/sndlecture.js
  src/components/page6(2nd)/sndquantum.js
  src/components/page6(2nd)/sndsyllabus.js
  src/components/page7(4yr)/frthsyllabus.js
  src/components/page8(3yr)/trdsyllabus.js
  src/components/review/review.jsx
Labels: gssoc, level1

#232 fix page width
  src/pages/header.css
Labels: gssoc, level1

#236 [Feature Request]: Want to Improve Ui of Pyq page #223
  src/components/page4/Pyq.css
  src/components/page4/pyq.js
Labels: gssoc, level2

#238 [Feature Request]: Want to Connect pages using Routes #224
  package-lock.json
  package.json
  src/App.js
  src/components/page5(1st)/fsttimetable.js
  src/index.js
  src/pages/Dashboard1.jsx
Labels: gssoc, level2

#245 [Bug]: Nav bar #218
  src/pages/header.js
Labels: gssoc, level1

#248 add timetable of 1st and 2nd year
  public/timetables/Sec 2C.jpg
  public/timetables/sec 1A.jpg
  public/timetables/sec 1C.jpg
  public/timetables/sec 1D.jpg
  public/timetables/sec 1E.jpg
  public/timetables/sec 1G.jpg
  public/timetables/sec 2A.jpg
  public/timetables/sec 2B.jpg
  public/timetables/sec 2D.jpg
  public/timetables/sec-1A.jpg
  src/components/page3/2Year.js
  src/components/page5(1st)/fsttimetable.js
  src/components/page6(2nd)/sndtimetable.js
Labels: gssoc, level3

#253 [Feature Request]: Add a functional download button for Timetables #244
  src/components/imgdata.css
  src/components/imgdata.js
Labels: gssoc, level2

#254 [Feature Request]: pages not opening from top #239
  src/App.js
  src/Content/ScrollToTop.jsx
Labels: gssoc, level1

#252 footer size has fixed
  src/components/page1/Home.css
  src/components/page4/Pyq.css
Labels: gssoc, level1

#249 [Bug]: Home page scroll #246
  src/components/page3/1Year.css
Labels: gssoc, level1
