Repository AbhiDiva96/75per, pull requests merged in 2024-05, with the labels that each got.

#24 added workflow as per issue #18
  .github/workflows/autocomment-pr-raise.yml
Labels: level1

#34 UI:Quantaum Ui needs upgradation #8
  src/assets/0ea60e02e5dbad89e04710fab40d7b21.jpg
  src/components/page3/1Year.css
  src/components/page4/quantum.css
  src/components/page4/trdquantum.js
  src/components/page5(1st)/fstquantum.css
  src/components/page5(1st)/fstquantum.js
  src/components/page6(2nd)/sndquantum.css
  src/components/page6(2nd)/sndquantum.js
  src/pages/header.js
Labels: gssoc, level2

#41 Added CONTRIBUTION.md
  CONTRIBUTION.md
Labels: documentation, gssoc, level1

#28 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: documentation, gssoc

#29 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: documentation, gssoc

#44 Feature: build backend of User Authentication #11
  package-lock.json
  package.json
  server.js
  src/App.js
  src/components/login/LoginSignup.css
  src/components/login/LoginSignup.jsx
  src/index.js
  src/pages/header.js
Labels: gssoc, level3
